solve the task
k1llzers/book-store pull request #1
Opened 2023-10-28 15:58 UTC by k1llzers

2023-10-28 16:16 UTC, sokimaaa commented on src/main/java/book/store/bookstore/models/Book.java
> +    @NotNull
@NotNull is annotation for validation purposes.

You need to add constraints on database level, for this use @Column annotation.

2023-10-28 16:18 UTC, sokimaaa commented on src/main/java/book/store/bookstore/repositories/BookRepository.java
> +public interface BookRepository extends JpaRepository<Book,Long> {
in this homework expected to write own implementation of BookRepository, e.g. using Hibernate
![image](https://github.com/k1llzers/book-store/assets/109764850/8f728eea-6be5-41b0-a3d6-d019fe813c68)

2023-10-29 08:16 UTC, Sanderfuck requested changes

2023-10-29 08:16 UTC, Sanderfuck commented on src/main/java/book/store/bookstore/repositorie/impl/BookRepositoryImpl.java
> +            throw new RuntimeException("Can`t insert book into DB: " + book,e);
You need space after "book," before commit code use Ctrl+Alt+L and Ctrl+Alt+O for cleaning code

2023-10-29 11:17 UTC, kerrrusha approved these changes

2023-10-29 11:17 UTC, kerrrusha commented on src/main/java/book/store/bookstore/model/Book.java
> +    @Column(unique = true,nullable = false)
```suggestion
    @Column(unique = true, nullable = false)
```

2023-10-29 11:21 UTC, merged